all: binomial binomial2 de mergesort prime_factors primes totient totient2

binomial: binomial.hs
	ghc -o binomial binomial.hs

binomial2: binomial2.hs
	ghc -o binomial2 binomial2.hs

de: de.hs
	ghc -o de de.hs

mergesort: mergesort.hs
	ghc -o mergesort mergesort.hs

prime_factors: prime_factors.hs
	ghc -o prime_factors prime_factors.hs

primes: primes.hs
	ghc -o primes primes.hs

totient: totient.hs
	ghc -o totient totient.hs

totient2: totient2.hs
	ghc -o totient2 totient2.hs

clean:
	rm -f *.hi *.o binomial binomial2 binomial binomial2 de mergesort prime_factors primes totient totient2